In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

Matplotlib is building the font cache; this may take a moment.

In [ ]:
import os
print(os.getcwd())


os.listdir("../data")

d:\sql-pizza-sales-project\python

['orders.csv', 'order_details.csv', 'pizzas.csv', 'pizza_types.csv']

In [7]:
import os

print(os.path.exists("../data/pizza_types.csv"))

True

In [ ]:
orders = pd.read_csv("../data/orders.csv")

order_details = pd.read_csv("../data/order_details.csv")

pizzas = pd.read_csv("../data/pizzas.csv")

pizza_types = pd.read_csv(
    "../data/pizza_types.csv",
    encoding="cp1252"
)

In [16]:
orders.head()

   order_id        date      time
0         1  2015-01-01  11:38:36
1         2  2015-01-01  11:57:40
2         3  2015-01-01  12:12:28
3         4  2015-01-01  12:16:31
4         5  2015-01-01  12:21:30

In [17]:
order_details.head()

   order_details_id  order_id       pizza_id  quantity
0                 1         1     hawaiian_m         1
1                 2         2  classic_dlx_m         1
2                 3         2  five_cheese_l         1
3                 4         2    ital_supr_l         1
4                 5         2     mexicana_m         1

In [18]:
pizzas.head()

     pizza_id pizza_type_id size  price
0   bbq_ckn_s       bbq_ckn    S  12.75
1   bbq_ckn_m       bbq_ckn    M  16.75
2   bbq_ckn_l       bbq_ckn    L  20.75
3  cali_ckn_s      cali_ckn    S  12.75
4  cali_ckn_m      cali_ckn    M  16.75

In [19]:
pizza_types.head()

,pizza_type_id,name,category,ingredients
0,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,..."
1,cali_ckn,The California Chicken Pizza,Chicken,"Chicken, Artichoke, Spinach, Garlic, Jalapeno ..."
2,ckn_alfredo,The Chicken Alfredo Pizza,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A..."
3,ckn_pesto,The Chicken Pesto Pizza,Chicken,"Chicken, Tomatoes, Red Peppers, Spinach, Garli..."
4,southw_ckn,The Southwest Chicken Pizza,Chicken,"Chicken, Tomatoes, Red Peppers, Red Onions, Ja..."

In [20]:
print("Orders:", orders.shape)
print("Order Details:", order_details.shape)
print("Pizzas:", pizzas.shape)
print("Pizza Types:", pizza_types.shape)

Orders: (21350, 3)
Order Details: (48620, 4)
Pizzas: (96, 4)
Pizza Types: (32, 4)

In [21]:
print(orders.isnull().sum())
print(order_details.isnull().sum())
print(pizzas.isnull().sum())
print(pizza_types.isnull().sum())

order_id    0
date        0
time        0
dtype: int64
order_details_id    0
order_id            0
pizza_id            0
quantity            0
dtype: int64
pizza_id         0
pizza_type_id    0
size             0
price            0
dtype: int64
pizza_type_id    0
name             0
category         0
ingredients      0
dtype: int64

In [22]:
print("Orders duplicates:", orders.duplicated().sum())
print("Order Details duplicates:", order_details.duplicated().sum())
print("Pizzas duplicates:", pizzas.duplicated().sum())
print("Pizza Types duplicates:", pizza_types.duplicated().sum())

Orders duplicates: 0
Order Details duplicates: 0
Pizzas duplicates: 0
Pizza Types duplicates: 0